// DataCarBox.js
import { HeartOutlined } from "@ant-design/icons";
import Rush from "../../assets/Rush.png"; 
import Crv from "../../assets/Crv.png";
import Terios from "../../assets/Terios.png";
import CrvTwo from "../../assets/CrvTwo.png";
import Exclusice from "../../assets/MGZXExclusice.png";
import NewMgZs from "../../assets/NewMGZS.png";
import Excite from "../../assets/MGZXExcite.png";
import TwoNewMgZs from "../../assets/NewMGZS (3).png";
import car from "../../assets/car.png";
import Nissan from "../../assets/nissangtr.png";
import Royce from "../../assets/Rolls-Royce.png";
import Gas from "../../assets/GasStation.png";
import Profiluser from "../../assets/user.png";
import Manual from "../../assets/Manual.png";
export const cars = [
  {
    id: 1,
    title: "All New Rush",
    type: "SUV",
    price: "$72.00",
    discount: "$80.00",
    image: Rush,
    people: "6 People",
    gas: "70L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 2,
    title: "CR-V",
    type: "SUV",
    price: "$80.00",
    discount: null,
    image: Crv,
    people: "6 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 3,
    title: "All New Terios",
    type: "SUV",
    price: "$74.00",
    discount: null,
    image: Terios,
    people: "6 People",
    gas: "90L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 4,
    title: "CR - V",
    type: "SUV",
    price: "$80.00",
    discount: null,
    image: CrvTwo,
    people: "6 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 5,
    title: "MG ZX Exclusice",
    type: "SUV",
    price: "$80.00",
    discount: "$80.00",
    image: Exclusice,
    people: "6 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 6,
    title: "New MG ZS",
    type: "SUV",
    price: "$80.00",
    discount: null,
    image: NewMgZs,
    people: "6 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 7,
    title: "MG ZX Excite",
    type: "Hatchback",
    price: "$74.00",
    discount: null,
    image: Excite,
    people: "6 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 8,
    title: "New MG ZS",
    type: "SUV",
    price: "$80.00",
    discount: null,
    image: TwoNewMgZs,
    people: "6 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[340px]",
    flex: "flex-col md:flex-row gap-4 md:w-full",
    CarFlex: "gap-[45px] flex-row md:flex-col",
    BoxImage: "w-[160px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 9,
    title: "Koenigsegg",
    type: "Sport",
    price: "$99.00",
    discount: null,
    image: car,
    people: "2 People",
    gas: "90L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[300px]",
    flex: "flex-row gap-4",
    CarFlex: "flex-col",
    BoxImage: "w-[220px] h-[64px] md:w-[264px] md:[108px]",
  },
  {
    id: 10,
    title: "Nissan GT - R",
    type: "Sport",
    price: "$80.00",
    discount: "$100.00",
    image: Nissan,
    people: "2 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[300px]",
    flex: "flex-row w-full",
    CarFlex: "flex-col",
    BoxImage: "w-[220px] h-[64px] md:w-[204px] md:[64px]",
  },
  {
    id: 11,
    title: "Rolls - Royce",
    type: "Sedan",
    price: "$96.00",
    discount: null,
    image: Royce,
    people: "4 People",
    gas: "70L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[300px]",
    flex: "flex-row w-full",
    CarFlex: "flex-col",
    BoxImage: "w-[220px] h-[64px] md:w-[204px] md:[64px]",
  },
  {
    id: 12,
    title: "Nissan GT - R",
    type: "Sport",
    price: "$80.00",
    discount: "$100.00",
    image: Nissan,
    people: "2 People",
    gas: "80L",
    heart: <HeartOutlined />,
    imageGas: Gas,
    imagePeople: Profiluser,
    imageManual: Manual,
    mobileWidth: "w-[300px]",
    flex: "flex-row w-full",
    CarFlex: "flex-col",
    BoxImage: "w-[220px] h-[64px] md:w-[204px] md:[64px]",
  },
];
